import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  

  return (
  <html lang="en">
      <body className ={inter.className}>
      
        <div className = "text-yellow-600  ">
        <Link className="mx-5 hover:text-gray-300 hover:cursor-pointer"href={'/notasShow'}>notas</Link>
        <Link className="mx-5 hover:text-gray-300 hover:cursor-pointer "href={'/tareasShow'}>tareas</Link>
        <Link className="mx-5 hover:text-gray-300 hover:cursor-pointer"href={'/notasCreate'}>crear notas</Link>
        <Link className="mx-5 hover:text-gray-300 hover:cursor-pointer"href={'/tareasCreate'}>crear tareas</Link>
        </div>

        {children}
      
      </body>
    </html>
  );
}
